/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolenguajes;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia Rodriguez
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Simulador de Voz");
        this.jl_diaActual.setText(dtf2.format(LocalDateTime.now()));
        conectarBaseDatos();
        thread = new Hilo(this);
        thread.start();
        threadHora = new HiloHora(this.jl_horaActual);
        threadHora.contadorReloj(this.jl_horaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_principal = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jd_crear = new javax.swing.JDialog();
        tf_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        cb_genero = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jl_ponerFoto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jd_buscar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_apellidoBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jd_bitacora = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_contactos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_bitacora = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jd_opcionesBuscar = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jd_mensaje = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jLabel46 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jd_videollamada = new javax.swing.JDialog();
        jl_tiempoVideollamada = new javax.swing.JLabel();
        jt_numeroVideollamada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jl_labelWebcam = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jd_buzon = new javax.swing.JDialog();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_buzon = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jd_llamada = new javax.swing.JDialog();
        jt_numeroLlamada = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jl_tiempoLlamada = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jd_seguroLlamada = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jd_seguroVideollamada = new javax.swing.JDialog();
        jLabel42 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jl_horaActual = new javax.swing.JLabel();
        jl_diaActual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jd_principal.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_principalWindowClosing(evt);
            }
        });
        jd_principal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/tables-512-iloveimg-resized.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 150));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/lupa icono-iloveimg-resized.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jd_principal.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, 150));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/contacts-iloveimg-resized.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_crear.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_crearWindowClosing(evt);
            }
        });
        jd_crear.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_crear.getContentPane().add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, -1));

        jLabel6.setText("Telefono");
        jd_crear.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel7.setText("Nombre");
        jd_crear.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel8.setText("Apellido");
        jd_crear.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel9.setText("E-Mail");
        jd_crear.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        jLabel10.setText("Genero");
        jd_crear.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));
        jd_crear.getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, -1));
        jd_crear.getContentPane().add(tf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 150, -1));
        jd_crear.getContentPane().add(tf_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 150, -1));

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));
        jd_crear.getContentPane().add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 150, -1));

        jLabel41.setText("Foto");
        jd_crear.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jl_ponerFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/name-iloveimg-resized-iloveimg-resized.png"))); // NOI18N
        jl_ponerFoto.setPreferredSize(new java.awt.Dimension(60, 60));
        jl_ponerFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_ponerFotoMouseClicked(evt);
            }
        });
        jd_crear.getContentPane().add(jl_ponerFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 100, 70));

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jd_crear.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 90, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/contacts-iloveimg-resized.png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 150));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_buscar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_buscarWindowClosing(evt);
            }
        });
        jd_buscar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        jLabel4.setText("Nombre");

        tf_apellidoBuscar.setEditable(false);

        jLabel5.setText("Apellido");

        tf_nombreBuscar.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_apellidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellidoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44))
        );

        jd_buscar.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 190));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jd_buscar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 100, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/lupa icono-iloveimg-resized.png"))); // NOI18N
        jd_buscar.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jLabel18.setText("Apellido");
        jd_buscar.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_buscar.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_bitacora.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_bitacoraWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_bitacoraWindowOpened(evt);
            }
        });
        jd_bitacora.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Apellido", "E-Mail", "Genero", "Foto (Ruta)"
            }
        ));
        jScrollPane1.setViewportView(jt_contactos);

        jd_bitacora.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 160));

        jt_bitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Acción", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(jt_bitacora);

        jd_bitacora.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 230));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Contactos");
        jd_bitacora.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 90, -1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Bitacora");
        jd_bitacora.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 90, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_bitacora.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_bitacora.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_opcionesBuscar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_opcionesBuscarWindowClosing(evt);
            }
        });
        jd_opcionesBuscar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/delete-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 140, 150));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/text message-iloveimg-resized.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jd_opcionesBuscar.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, 150));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/phone-512-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 140, 150));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/modificar-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 150));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_mensaje.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_mensajeWindowClosing(evt);
            }
        });
        jd_mensaje.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane3.setViewportView(ta_mensaje);

        jd_mensaje.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 360));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/mailbox-iloveimg-resized.png"))); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jd_mensaje.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, 150));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/text message-iloveimg-resized.png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 150));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_videollamada.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_videollamadaWindowOpened(evt);
            }
        });
        jd_videollamada.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_tiempoVideollamada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jl_tiempoVideollamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_videollamada.getContentPane().add(jl_tiempoVideollamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 90, 20));

        jt_numeroVideollamada.setEditable(false);
        jt_numeroVideollamada.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jt_numeroVideollamada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jd_videollamada.getContentPane().add(jt_numeroVideollamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 190, 50));

        jl_labelWebcam.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_labelWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_labelWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jd_videollamada.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 310));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/videocall-iloveimg-resized.png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 150));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_buzon.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_buzonWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_buzonWindowOpened(evt);
            }
        });
        jd_buzon.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/mailbox-iloveimg-resized.png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jt_buzon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Mensaje", "Nombre", "Apellido"
            }
        ));
        jScrollPane5.setViewportView(jt_buzon);

        jd_buzon.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 170));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_llamada.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_llamadaWindowOpened(evt);
            }
        });
        jd_llamada.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_numeroLlamada.setEditable(false);
        jt_numeroLlamada.setBackground(new java.awt.Color(102, 255, 102));
        jt_numeroLlamada.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jt_numeroLlamada.setForeground(new java.awt.Color(255, 255, 255));
        jt_numeroLlamada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jd_llamada.getContentPane().add(jt_numeroLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 70));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/largo.PNG"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 20));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/largo.PNG"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 200, 20));

        jl_tiempoLlamada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jl_tiempoLlamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_llamada.getContentPane().add(jl_tiempoLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 120, 20));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170317-152653-iloveimg-resized.png"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_seguroLlamada.setPreferredSize(new java.awt.Dimension(360, 125));

        jLabel31.setText("¿Seguro que quiere realizar esta llamada?");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/info-iloveimg-resized.png"))); // NOI18N

        jButton4.setText("Si");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("No");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_seguroLlamadaLayout = new javax.swing.GroupLayout(jd_seguroLlamada.getContentPane());
        jd_seguroLlamada.getContentPane().setLayout(jd_seguroLlamadaLayout);
        jd_seguroLlamadaLayout.setHorizontalGroup(
            jd_seguroLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_seguroLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jd_seguroLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_seguroLlamadaLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_seguroLlamadaLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45))))
        );
        jd_seguroLlamadaLayout.setVerticalGroup(
            jd_seguroLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_seguroLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_seguroLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(jd_seguroLlamadaLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_seguroLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jd_seguroVideollamada.setPreferredSize(new java.awt.Dimension(360, 125));

        jLabel42.setText("¿Seguro que quiere realizar esta videollamada?");

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/info-iloveimg-resized.png"))); // NOI18N

        jButton6.setText("Si");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("No");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_seguroVideollamadaLayout = new javax.swing.GroupLayout(jd_seguroVideollamada.getContentPane());
        jd_seguroVideollamada.getContentPane().setLayout(jd_seguroVideollamadaLayout);
        jd_seguroVideollamadaLayout.setHorizontalGroup(
            jd_seguroVideollamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_seguroVideollamadaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_seguroVideollamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_seguroVideollamadaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(2, 2, 2)
                        .addComponent(jButton7)
                        .addGap(39, 39, 39))
                    .addGroup(jd_seguroVideollamadaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))
        );
        jd_seguroVideollamadaLayout.setVerticalGroup(
            jd_seguroVideollamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_seguroVideollamadaLayout.createSequentialGroup()
                .addGroup(jd_seguroVideollamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_seguroVideollamadaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_seguroVideollamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(26, 26, 26))
                    .addGroup(jd_seguroVideollamadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        tf_usuario.setEditable(false);

        tf_contra.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(tf_contra))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 190));

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));

        jl_horaActual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_horaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jl_diaActual.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jl_diaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_horaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_diaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jl_horaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_diaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 150));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tf_usuario.getText().equalsIgnoreCase("five") && tf_contra.getText().equalsIgnoreCase("seven")) {
            this.setVisible(false);
            this.jd_principal.setModal(true);
            this.jd_principal.pack();
            this.jd_principal.setLocationRelativeTo(this);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }
        this.tf_usuario.setText("");
        this.tf_contra.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Contacts values (?,?,?,?,?,?)");
            int telefono = Integer.parseInt(tf_telefono.getText());
            String nombre = tf_nombre.getText();
            String apellido = tf_apellido.getText();
            String email = tf_mail.getText();
            String genero = cb_genero.getSelectedItem().toString();
            statement.setInt(1, telefono);
            statement.setString(2, nombre);
            statement.setString(3, apellido);
            statement.setString(4, email);
            statement.setString(5, genero);
            statement.setString(6, path.getPath());
            this.tf_telefono.setText("");
            this.tf_nombre.setText("");
            this.tf_apellido.setText("");
            this.tf_mail.setText("");
            this.cb_genero.setSelectedIndex(0);
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Contacto creado");
            
            statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha creado un contacto.");
            statement.setString(3, nombre);
            statement.setString(4, apellido);
            statement.executeUpdate();
            this.jd_crear.setVisible(false);
            this.jd_principal.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jd_bitacoraWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_bitacoraWindowOpened
        actualizarBitacora(jt_bitacora);
        actualizarContacto(jt_contactos);        
    }//GEN-LAST:event_jd_bitacoraWindowOpened

    private void jd_videollamadaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_videollamadaWindowOpened
        try {
            webcam = Webcam.getDefault();
            WebcamPanel panel = new WebcamPanel(webcam);
            panel.setFPSDisplayed(true);
            panel.setFillArea(true);
            panel.setSize(320, 310);
            jl_labelWebcam.add(panel);
        } catch (Exception e) {
            e.printStackTrace();
        }
        tiempoVideollamada.contadorRelojLlamada(this.jl_tiempoVideollamada);
    }//GEN-LAST:event_jd_videollamadaWindowOpened

    private void jd_principalWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_principalWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_jd_principalWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nombreBuscar = tf_nombreBuscar.getText();
        apellidoBuscar = tf_apellidoBuscar.getText();
        try{
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select* from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            if (rs.next()) {
                this.jt_numeroLlamada.setText(rs.getInt(1)+"");
                this.jt_numeroVideollamada.setText(rs.getInt(1)+"");
                this.jd_buscar.setVisible(false);
                this.jd_opcionesBuscar.setModal(true);
                this.jd_opcionesBuscar.pack();
                this.jd_opcionesBuscar.setLocationRelativeTo(this);
                this.jd_opcionesBuscar.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(this, "El contacto no existe.");
            }
            this.tf_nombreBuscar.setText("");
            this.tf_apellidoBuscar.setText("");
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jd_buzonWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_buzonWindowOpened
        actualizarMensaje(jt_buzon);
    }//GEN-LAST:event_jd_buzonWindowOpened

    private void jd_llamadaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_llamadaWindowOpened
        tiempoLlamada.contadorRelojLlamada(this.jl_tiempoLlamada);
    }//GEN-LAST:event_jd_llamadaWindowOpened

    private void jl_ponerFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_ponerFotoMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fileChooser.setFileFilter(filtro);
        File file;
        int opcion = fileChooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            path = file;
            Image image = Toolkit.getDefaultToolkit().createImage(file.getPath()).getScaledInstance(100, 70, 0);
            this.jl_ponerFoto.setIcon(new ImageIcon(image));
        } else {
            path = null;
        }
    }//GEN-LAST:event_jl_ponerFotoMouseClicked

    private void jd_crearWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_crearWindowClosing
        this.jd_crear.dispose();
        this.jd_principal.setVisible(true);
    }//GEN-LAST:event_jd_crearWindowClosing

    private void jd_buscarWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_buscarWindowClosing
        this.jd_buscar.dispose();
        this.jd_principal.setVisible(true);
    }//GEN-LAST:event_jd_buscarWindowClosing

    private void jd_bitacoraWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_bitacoraWindowClosing
        this.jd_bitacora.dispose();
        this.jd_principal.setVisible(true);
    }//GEN-LAST:event_jd_bitacoraWindowClosing

    private void jd_buzonWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_buzonWindowClosing
        this.jd_buzon.dispose();
        this.jd_mensaje.setVisible(true);
    }//GEN-LAST:event_jd_buzonWindowClosing

    private void jd_opcionesBuscarWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_opcionesBuscarWindowClosing
        this.jd_opcionesBuscar.setVisible(false);
        this.jd_buscar.setVisible(true);
    }//GEN-LAST:event_jd_opcionesBuscarWindowClosing

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        enseñarBuscar();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        enseñarMensaje();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        enseñarBuzon();
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jd_mensajeWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_mensajeWindowClosing
        this.jd_mensaje.setVisible(false);
        this.jd_principal.setVisible(true);
    }//GEN-LAST:event_jd_mensajeWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jd_seguroLlamada.dispose();
        this.enseñarLlamada();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jd_seguroVideollamada.dispose();
        this.enseñarVideollamada();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(this, "No se realizara la llamada.");
        this.jd_seguroLlamada.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(this, "No se realizara la videollamada.");
        this.jd_seguroVideollamada.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDialog jd_bitacora;
    private javax.swing.JDialog jd_buscar;
    private javax.swing.JDialog jd_buzon;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_llamada;
    private javax.swing.JDialog jd_mensaje;
    private javax.swing.JDialog jd_opcionesBuscar;
    private javax.swing.JDialog jd_principal;
    private javax.swing.JDialog jd_seguroLlamada;
    private javax.swing.JDialog jd_seguroVideollamada;
    private javax.swing.JDialog jd_videollamada;
    private javax.swing.JLabel jl_diaActual;
    private javax.swing.JLabel jl_horaActual;
    private javax.swing.JLabel jl_labelWebcam;
    private javax.swing.JLabel jl_ponerFoto;
    private javax.swing.JLabel jl_tiempoLlamada;
    private javax.swing.JLabel jl_tiempoVideollamada;
    private javax.swing.JTable jt_bitacora;
    private javax.swing.JTable jt_buzon;
    private javax.swing.JTable jt_contactos;
    private javax.swing.JTextField jt_numeroLlamada;
    private javax.swing.JTextField jt_numeroVideollamada;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_apellidoBuscar;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreBuscar;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    Connection connect;
    Hilo thread;
    HiloHora threadHora;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String nombreBuscar, apellidoBuscar;
    ArrayList listaCambio = new ArrayList();
    HiloTimer tiempoLlamada = new HiloTimer(this.jl_tiempoLlamada);
    HiloTimer tiempoVideollamada = new HiloTimer(this.jl_tiempoVideollamada);
    File path = null;
    Webcam webcam;
    
    public void conectarBaseDatos() {
        try {
            String connectionUrl = "jdbc:sqlserver://;database=TablasLenguajes;integratedSecurity=true;";
            connect = DriverManager.getConnection(connectionUrl);
            System.out.println("Se ha conectado exitosamente.");
        } catch (SQLException ex) {
            System.out.println("Ha ocurrido un error.");
            ex.printStackTrace();
        }
    }
    
    public void usuarioTextField() {
        if (this.isVisible() && !this.tf_usuario.isFocusOwner()) {
            this.tf_usuario.grabFocus();
        }
    }

    public void contraTextField() {
        if (this.isVisible() && !this.tf_contra.isFocusOwner()) {
            this.tf_contra.grabFocus();
        }
    }
    
    public void nombreTextField(String nombre) {
        if (this.getFocusOwner() instanceof JTextField) {
            ((JTextField)this.getFocusOwner()).setText(nombre);
        }
    }
    
    public void buscarTextField(String nombre) {
        if (this.jd_buscar.getFocusOwner() instanceof JTextField) {
            ((JTextField)this.jd_buscar.getFocusOwner()).setText(nombre);
        }
    }
    
    public void nombreBuscarTextField() {
        if (this.jd_buscar.isVisible() && !this.tf_nombreBuscar.isFocusOwner()) {
            this.tf_nombreBuscar.grabFocus();
        }
    }

    public void apellidoBuscarTextField() {
        if (this.jd_buscar.isVisible() && !this.tf_apellidoBuscar.isFocusOwner()) {
            this.tf_apellidoBuscar.grabFocus();
        }
    }
    
    public boolean principalVisibleONo(){
        boolean visible = false;
        if (this.jd_principal.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public boolean buscarVisibleONo(){
        boolean visible = false;
        if (this.jd_buscar.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public boolean opcionesVisibleONo(){
        boolean visible = false;
        if (this.jd_opcionesBuscar.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public boolean mensajeVisibleONo(){
        boolean visible = false;
        if (this.jd_mensaje.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public boolean videoLlamadaVisibleONo(){
        boolean visible = false;
        if (this.jd_videollamada.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public boolean llamadaVisibleONo(){
        boolean visible = false;
        if (this.jd_llamada.isVisible()) {
            visible = true;
        }
        return visible;
    }
    
    public void enseñarCrear(){
        this.jd_principal.setVisible(false);
        this.jd_crear.setModal(true);
        this.jd_crear.pack();
        this.jd_crear.setLocationRelativeTo(this);
        this.jd_crear.setVisible(true);
    }
    
    public void enseñarBitacora(){
        this.jd_principal.setVisible(false);
        this.jd_bitacora.setModal(true);
        this.jd_bitacora.pack();
        this.jd_bitacora.setLocationRelativeTo(this);
        this.jd_bitacora.setVisible(true);
    }
    
    public void enseñarBuscar(){
        this.jd_principal.setVisible(false);
        this.jd_buscar.setModal(true);
        this.jd_buscar.pack();
        this.jd_buscar.setLocationRelativeTo(this);
        this.jd_buscar.setVisible(true);
    }
    
    public void enseñarBuzon(){
        this.jd_mensaje.setVisible(false);
        this.jd_buzon.setModal(true);
        this.jd_buzon.pack();
        this.jd_buzon.setLocationRelativeTo(this);
        this.jd_buzon.setVisible(true);
    }
    
    public void enseñarVideollamada(){
        this.jd_opcionesBuscar.setVisible(false);
        this.jd_videollamada.setModal(true);
        this.jd_videollamada.pack();
        this.jd_videollamada.setLocationRelativeTo(this);
        this.jd_videollamada.setVisible(true);
    }
    
    public void enseñarLlamada(){
        this.jd_opcionesBuscar.setVisible(false);
        this.jd_llamada.setModal(true);
        this.jd_llamada.pack();
        this.jd_llamada.setLocationRelativeTo(this);
        this.jd_llamada.setVisible(true);
    }
    
    public void enseñarMensaje(){
        this.jd_opcionesBuscar.setVisible(false);
        this.jd_mensaje.setModal(true);
        this.jd_mensaje.pack();
        this.jd_mensaje.setLocationRelativeTo(this);
        this.jd_mensaje.setVisible(true);
    }
    
    public void cerrarVideollamada(){
        try{
            PreparedStatement statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se realizó una videollamada que duró ."+this.jl_tiempoVideollamada.getText());
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            statement.executeUpdate();
        }catch(SQLException e){
            e.printStackTrace();
        }
        webcam.close();
        this.jd_videollamada.dispose();
        tiempoVideollamada.cancel();
        this.jd_principal.setVisible(true);
    }
    
    public void cerrarLlamada(){
        try{
            PreparedStatement statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se realizó una llamada que duró ."+this.jl_tiempoLlamada.getText());
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            statement.executeUpdate();
        }catch(SQLException e){
            e.printStackTrace();
        }
        this.jd_llamada.dispose();
        tiempoLlamada.cancel();
        this.jd_principal.setVisible(true);
    }
    
    public void cerrarMensaje(){
        this.jd_mensaje.setVisible(false);
        this.jd_principal.setVisible(true);
    }
    
    public int conteoParaBitacora() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(fecha) from Bitacora;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
     int conteoParaContactos() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(numero) from Contacts;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
    public int conteoParaMensaje() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(fecha) from Mensaje;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
    public String[] nombreBitacora() {
        String[] nombre = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoBitacora() {
        String[] apellido = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public String[] fechaBitacora() {
        String[] fecha = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select fecha from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                fecha[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fecha;
    }
    
    public String[] accionBitacora() {
        String[] accion = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select accion from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                accion[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return accion;
    }
    
    public int[] numeroContactos() {
        int[] numero = new int[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select numero from Contacts;");
            int contador = 0;
            while (rs.next()) {
                numero[contador] = rs.getInt(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return numero;
    }
    
    public String[] nombreContactos() {
        String[] nombre = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Contacts;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoContactos() {
        String[] apellido = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Contacts;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public String[] mailContactos() {
        String[] mail = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select email from Contacts;");
            int contador = 0;
            while (rs.next()) {
                mail[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return mail;
    }
    
    public String[] generoContactos() {
        String[] genero = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select genero from Contacts;");
            int contador = 0;
            while (rs.next()) {
                genero[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return genero;
    }
    
    public String[] fotoContactos() {
        String[] foto = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select foto from Contacts;");
            int contador = 0;
            while (rs.next()) {
                foto[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return foto;
    }
    
    public String[] fechaMensaje() {
        String[] fecha = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select fecha from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                fecha[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fecha;
    }
    
    public String[] mensajeMensaje() {
        String[] mensaje = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select mensaje from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                mensaje[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return mensaje;
    }
    
    public String[] nombreMensaje() {
        String[] nombre = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoMensaje() {
        String[] apellido = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public ArrayList listaParaCambio(String nombreBuscar, String apellidoBuscar){
        ArrayList lista = new ArrayList();
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select numero from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getInt(1));
            }
            rs = statement.executeQuery("select nombre from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select apellido from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select email from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select genero from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select foto from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return lista;
    }
    
    public void cambiarNumero() {
        String nuevo = JOptionPane.showInputDialog(this, "Escriba el nuevo numero", "Cambio de numero"
                ,JOptionPane.QUESTION_MESSAGE);
        if (nuevo != null) {
            int nuevoNumero = Integer.parseInt(nuevo);
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                String foto = (String)listaCambio.get(5);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, nuevoNumero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.setString(6, foto);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el numero.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el numero de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio el numero.");
        }
    }
    
    public void cambiarNombre() {
        String nuevoNombre = JOptionPane.showInputDialog(this, "Escriba el nuevo nombre", "Cambio de nombre"
                ,JOptionPane.QUESTION_MESSAGE);
        if (nuevoNombre != null) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                String foto = (String)listaCambio.get(5);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, numero);
                    update.setString(2, nuevoNombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.setString(6, foto);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el nombre.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el nombre de un contacto");
                preparedStatement.setString(3, nuevoNombre);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio el nombre.");
        }
    }
    
    public void cambiarApellido() {
        String nuevoApellido = JOptionPane.showInputDialog(this, "Escriba el nuevo apellido", "Cambio de apellido"
                ,JOptionPane.QUESTION_MESSAGE);
        if (nuevoApellido != null) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                String foto = (String)listaCambio.get(5);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, nuevoApellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.setString(6, foto);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el apellido.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el apellido de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, nuevoApellido);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio el apellido.");
        }
    }
    
    public void cambiarMail() {
        String nuevoMail = JOptionPane.showInputDialog(this, "Escriba el nuevo email", "Cambio de email"
                ,JOptionPane.QUESTION_MESSAGE);
        if (nuevoMail != null) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String genero = (String)listaCambio.get(4);
                String foto = (String)listaCambio.get(5);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, nuevoMail);
                    update.setString(5, genero);
                    update.setString(6, foto);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el email.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el email de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio el email.");
        }
    }
    
    public void cambiarGenero() {
        String nuevoGenero = JOptionPane.showInputDialog(this, "Escriba el nuevo genero", "Cambio de genero"
                ,JOptionPane.QUESTION_MESSAGE);
        if (nuevoGenero != null) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String foto = (String)listaCambio.get(5);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, nuevoGenero);
                    update.setString(6, foto);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el genero.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el genero de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio el genero.");
        }
    }
    
    public void cambiarFoto() {
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fileChooser.setFileFilter(filtro);
        File file;
        int opcion = fileChooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            path = file;
        }
        if (path != null) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?, foto = ? where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.setString(6, path.getPath());
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado la foto.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado la foto de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se cambio la foto.");
        }
    }
    
    public void borrarContacto(){
        int seguro = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este contacto?");
        if (seguro == JOptionPane.YES_OPTION) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement delete = connect.prepareStatement("delete from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    delete.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha borrado el contacto.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha borrado un contacto.");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
            this.jd_principal.setVisible(true);
        }
    }
    
    public void nombrarTablaContacto(String [] columnas){
        columnas [0] = "Numero";
        columnas [1] = "Nombre";
        columnas [2] = "Apellido";
        columnas [3] = "E-mail";
        columnas [4] = "Genero";
        columnas [5] = "Foto (Ruta)";
    }
    
    public void nombrarTablaBitacora(String [] columnas){
        columnas [0] = "Fecha";
        columnas [1] = "Acción";
        columnas [2] = "Nombre";
        columnas [3] = "Apellido";
    }
    
    public void nombrarTablaMensaje(String [] columnas){
        columnas [0] = "Fecha";
        columnas [1] = "Mensaje";
        columnas [2] = "Nombre";
        columnas [3] = "Apellido";
    }
    
    public void mandarMensaje(){
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Mensaje values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, ta_mensaje.getText());
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            statement.executeUpdate();
            
            statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha enviado un mensaje.");
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            statement.executeUpdate();
            
            this.ta_mensaje.setText("");
            actualizarMensaje(jt_buzon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void actualizarBitacora(JTable jt_bitacora){
        String[] columnas = new String[4];
        nombrarTablaBitacora(columnas);
        int size = conteoParaBitacora();
        String[][] contenido = new String[size][4];
        String[] fecha = fechaBitacora();
        String[] accion = accionBitacora();
        String[] nombre = nombreBitacora();
        String[] apellido = apellidoBitacora();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = fecha[i]+ "";
            contenido[i][1] = accion[i]+ "";
            contenido[i][2] = nombre[i]+ "";
            contenido[i][3] = apellido[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_bitacora.setModel(modelo);
    }
    
    public void actualizarContacto(JTable jt_contactos){
        String [] columnas = new String[6];
        nombrarTablaContacto(columnas);
        int size = conteoParaContactos();
        String [][] contenido = new String[size][6];
        int[] numero = numeroContactos();
        String[] nombreContacto = nombreContactos();
        String[] apellidoContacto = apellidoContactos();
        String[] mail = mailContactos();
        String[] genero = generoContactos();
        String[] foto = fotoContactos();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = numero[i]+ "";
            contenido[i][1] = nombreContacto[i]+ "";
            contenido[i][2] = apellidoContacto[i]+ "";
            contenido[i][3] = mail[i]+ "";
            contenido[i][4] = genero[i]+ "";
            contenido[i][5] = foto[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_contactos.setModel(modelo);
    }
    
    public void actualizarMensaje(JTable jt_buzon){
        String[] columnas = new String[4];
        nombrarTablaMensaje(columnas);
        int size = conteoParaMensaje();
        String[][] contenido = new String[size][4];
        String[] fecha = fechaMensaje();
        String[] mensaje = mensajeMensaje();
        String[] nombre = nombreMensaje();
        String[] apellido = apellidoMensaje();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = fecha[i]+ "";
            contenido[i][1] = mensaje[i]+ "";
            contenido[i][2] = nombre[i]+ "";
            contenido[i][3] = apellido[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_buzon.setModel(modelo);
    }
    
    public void seguroLlamada(){
        this.jd_seguroLlamada.setModal(true);
        this.jd_seguroLlamada.pack();
        this.jd_seguroLlamada.setLocationRelativeTo(this);
        this.jd_seguroLlamada.setVisible(true);
    }
    
    public void seguroVideoLlamada(){
        this.jd_seguroVideollamada.setModal(true);
        this.jd_seguroVideollamada.pack();
        this.jd_seguroVideollamada.setLocationRelativeTo(this);
        this.jd_seguroVideollamada.setVisible(true);
    }
}
