/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolenguajes;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia Rodriguez
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Simulador de Voz");
        conectarBaseDatos();
        thread = new Hilo(this);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_principal = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jd_crear = new javax.swing.JDialog();
        tf_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        cb_genero = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jd_buscar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreBuscar = new javax.swing.JTextField();
        tf_apellidoBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jd_bitacora = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_contactos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_bitacora = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jd_opcionesBuscar = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_nombreBuscarOpciones = new javax.swing.JTextField();
        tf_apellidoBuscarOpciones = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jd_telefono = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jd_mensaje = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jd_videollamada = new javax.swing.JDialog();
        jl_tiempoVideollamada = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jl_labelWebcam = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jd_buzon = new javax.swing.JDialog();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_buzon = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jd_marcando = new javax.swing.JDialog();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jd_llamada = new javax.swing.JDialog();
        jTextField3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jl_tiempoLlamada = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jd_principal.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_principalWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_principalWindowOpened(evt);
            }
        });
        jd_principal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/tabla-iloveimg-resized.jpg"))); // NOI18N
        jd_principal.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 150));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/lupa icono-iloveimg-resized.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, 150));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/contactos-iloveimg-resized.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_principal.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_crear.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jd_crear.getContentPane().add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, -1));

        jLabel6.setText("Telefono");
        jd_crear.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel7.setText("Nombre");
        jd_crear.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel8.setText("Apellido");
        jd_crear.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel9.setText("E-Mail");
        jd_crear.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        jLabel10.setText("Genero");
        jd_crear.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));
        jd_crear.getContentPane().add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, -1));
        jd_crear.getContentPane().add(tf_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 150, -1));
        jd_crear.getContentPane().add(tf_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 150, -1));

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));
        jd_crear.getContentPane().add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 150, -1));

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jd_crear.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 90, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/contactos-iloveimg-resized.png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 150));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_crear.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_buscar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre");
        jd_buscar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel5.setText("Apellido");
        jd_buscar.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));
        jd_buscar.getContentPane().add(tf_nombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, -1));
        jd_buscar.getContentPane().add(tf_apellidoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 130, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jd_buscar.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 100, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/lupa icono-iloveimg-resized.png"))); // NOI18N
        jd_buscar.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jLabel18.setText("Apellido");
        jd_buscar.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_buscar.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_bitacora.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_bitacoraWindowOpened(evt);
            }
        });
        jd_bitacora.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Apellido", "E-Mail", "Genero"
            }
        ));
        jScrollPane1.setViewportView(jt_contactos);

        jd_bitacora.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 90));

        jt_bitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Acción", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(jt_bitacora);

        jd_bitacora.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 90));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Contactos");
        jd_bitacora.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 90, -1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Bitacora");
        jd_bitacora.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_bitacora.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_bitacora.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_opcionesBuscar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/delete-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 140, 150));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/mensajes-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, 150));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/telefono-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 140, 150));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/modificar-iloveimg-resized.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 150));
        jd_opcionesBuscar.getContentPane().add(tf_nombreBuscarOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, -1));
        jd_opcionesBuscar.getContentPane().add(tf_apellidoBuscarOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_opcionesBuscar.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_telefono.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-182655-iloveimg-resized-iloveimg-resized (1).png"))); // NOI18N
        jd_telefono.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_telefono.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_mensaje.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane3.setViewportView(ta_mensaje);

        jd_mensaje.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 360));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/mensajes-iloveimg-resized.png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, 150));

        jButton4.setText("Mandar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jd_mensaje.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 90, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_mensaje.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_videollamada.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_videollamadaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_videollamadaWindowOpened(evt);
            }
        });
        jd_videollamada.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_tiempoVideollamada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jl_tiempoVideollamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_videollamada.getContentPane().add(jl_tiempoVideollamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 70, 20));

        jl_labelWebcam.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_labelWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_labelWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jd_videollamada.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 310));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/videocall-iloveimg-resized.png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 150));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_videollamada.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_buzon.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_buzonWindowOpened(evt);
            }
        });
        jd_buzon.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/mailbox-iloveimg-resized.png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 150));

        jt_buzon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Mensaje", "Nombre", "Apellido"
            }
        ));
        jScrollPane5.setViewportView(jt_buzon);

        jd_buzon.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 170));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_buzon.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_marcando.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/verde.PNG"))); // NOI18N
        jd_marcando.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 60));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/largo.PNG"))); // NOI18N
        jd_marcando.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 200, 20));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170317-152653-iloveimg-resized.png"))); // NOI18N
        jd_marcando.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_marcando.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_llamada.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_llamadaWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jd_llamadaWindowOpened(evt);
            }
        });
        jd_llamada.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(102, 255, 102));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jd_llamada.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 70));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/largo.PNG"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 200, 20));

        jl_tiempoLlamada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jl_tiempoLlamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jd_llamada.getContentPane().add(jl_tiempoLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 20));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170317-152653-iloveimg-resized.png"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        jd_llamada.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        tf_contra.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(tf_contra))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 190));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/Screenshot_20170312-131549.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 570));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolenguajes/galaxy j7-iloveimg-resized (1)-iloveimg-resized (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tf_usuario.getText().equalsIgnoreCase("mark") && tf_contra.getText().equalsIgnoreCase("seven")) {
            this.setVisible(false);
            this.jd_principal.setModal(true);
            this.jd_principal.pack();
            this.jd_principal.setLocationRelativeTo(this);
            this.jd_principal.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }
        this.tf_usuario.setText("");
        this.tf_contra.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Contacts values (?,?,?,?,?)");
            int telefono = Integer.parseInt(tf_telefono.getText());
            String nombre = tf_nombre.getText();
            String apellido = tf_apellido.getText();
            String email = tf_mail.getText();
            String genero = cb_genero.getSelectedItem().toString();
            statement.setInt(1, telefono);
            statement.setString(2, nombre);
            statement.setString(3, apellido);
            statement.setString(4, email);
            statement.setString(5, genero);
            this.tf_telefono.setText("");
            this.tf_nombre.setText("");
            this.tf_apellido.setText("");
            this.tf_mail.setText("");
            this.cb_genero.setSelectedIndex(0);
            int retorno = statement.executeUpdate();
            if (retorno > 0) {
                JOptionPane.showMessageDialog(this, "Contacto creado");
            }
            statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha creado un contacto.");
            statement.setString(3, nombre);
            statement.setString(4, apellido);
            int prueba2 = statement.executeUpdate();
            if (prueba2 > 0) {
                System.out.println("Bitacora actualizada.");
            }
            this.jd_crear.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jd_bitacoraWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_bitacoraWindowOpened
        String[] columnas = new String[4];
        int size = conteoParaBitacora();
        String[][] contenido = new String[size][4];
        String[] fecha = fechaBitacora();
        String[] accion = accionBitacora();
        String[] nombre = nombreBitacora();
        String[] apellido = apellidoBitacora();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = fecha[i]+ "";
            contenido[i][1] = accion[i]+ "";
            contenido[i][2] = nombre[i]+ "";
            contenido[i][3] = apellido[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_bitacora.setModel(modelo);
        
        columnas = new String[5];
        size = conteoParaContactos();
        contenido = new String[size][5];
        int[] numero = numeroContactos();
        String[] nombreContacto = nombreContactos();
        String[] apellidoContacto = apellidoContactos();
        String[] mail = mailContactos();
        String[] genero = generoContactos();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = numero[i]+ "";
            contenido[i][1] = nombreContacto[i]+ "";
            contenido[i][2] = apellidoContacto[i]+ "";
            contenido[i][3] = mail[i]+ "";
            contenido[i][4] = genero[i]+ "";
        }
        DefaultTableModel modelo2 = new DefaultTableModel(contenido, columnas);
        jt_contactos.setModel(modelo2);
    }//GEN-LAST:event_jd_bitacoraWindowOpened

    private void jd_videollamadaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_videollamadaWindowOpened
        try {
            Webcam webcam = Webcam.getDefault();
            WebcamPanel panel = new WebcamPanel(webcam);
            panel.setFPSDisplayed(true);
            panel.setFillArea(true);
            panel.setSize(320, 310);
            jl_labelWebcam.add(panel);
        } catch (Exception e) {
            e.printStackTrace();
        }
        tiempoVideollamada.contadorRelojLlamada(this.jl_tiempoVideollamada);
    }//GEN-LAST:event_jd_videollamadaWindowOpened

    private void jd_principalWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_principalWindowOpened
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha abierto el simulador");
            statement.setString(3, "NULL");
            statement.setString(4, "NULL");
            int prueba = statement.executeUpdate();
            if (prueba > 0) {
                System.out.println("Bitacora actualizada.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jd_principalWindowOpened

    private void jd_principalWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_principalWindowClosing
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha cerrado el simulador");
            statement.setString(3, "NULL");
            statement.setString(4, "NULL");
            int prueba = statement.executeUpdate();
            if (prueba > 0) {
                System.out.println("Bitacora actualizada.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setVisible(true);
    }//GEN-LAST:event_jd_principalWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tf_nombreBuscar.getText().equalsIgnoreCase("yo") && tf_apellidoBuscar.getText().equalsIgnoreCase("tu")) {
            nombreBuscar = tf_nombreBuscar.getText();
            apellidoBuscar = tf_apellidoBuscar.getText();
            this.jd_buscar.setVisible(false);
            this.jd_opcionesBuscar.setModal(true);
            this.jd_opcionesBuscar.pack();
            this.jd_opcionesBuscar.setLocationRelativeTo(this);
            this.jd_opcionesBuscar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "El contacto no existe.");
        }
        this.tf_nombreBuscar.setText("");
        this.tf_apellidoBuscar.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            PreparedStatement statement = connect.prepareStatement("Insert into Mensaje values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, ta_mensaje.getText());
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            int prueba = statement.executeUpdate();
            if (prueba > 0) {
                System.out.println("Bitacora actualizada.");
            }
            statement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
            statement.setString(1, dtf.format(LocalDateTime.now()));
            statement.setString(2, "Se ha enviado un mensaje.");
            statement.setString(3, nombreBuscar);
            statement.setString(4, apellidoBuscar);
            prueba = statement.executeUpdate();
            if (prueba > 0) {
                System.out.println("Bitacora actualizada.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jd_buzonWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_buzonWindowOpened
        String[] columnas = new String[4];
        int size = conteoParaMensaje();
        String[][] contenido = new String[size][4];
        String[] fecha = fechaMensaje();
        String[] mensaje = mensajeMensaje();
        String[] nombre = nombreMensaje();
        String[] apellido = apellidoMensaje();
        for (int i = 0; i < size; i++) {
            contenido[i][0] = fecha[i]+ "";
            contenido[i][1] = mensaje[i]+ "";
            contenido[i][2] = nombre[i]+ "";
            contenido[i][3] = apellido[i]+ "";
        }
        DefaultTableModel modelo = new DefaultTableModel(contenido, columnas);
        jt_buzon.setModel(modelo);
    }//GEN-LAST:event_jd_buzonWindowOpened

    private void jd_llamadaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_llamadaWindowOpened
        tiempoLlamada.contadorRelojLlamada(this.jl_tiempoLlamada);
    }//GEN-LAST:event_jd_llamadaWindowOpened

    private void jd_llamadaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_llamadaWindowClosing
        tiempoLlamada.cancel();
    }//GEN-LAST:event_jd_llamadaWindowClosing

    private void jd_videollamadaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_videollamadaWindowClosing
        tiempoVideollamada.cancel();
    }//GEN-LAST:event_jd_videollamadaWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JDialog jd_bitacora;
    private javax.swing.JDialog jd_buscar;
    private javax.swing.JDialog jd_buzon;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_llamada;
    private javax.swing.JDialog jd_marcando;
    private javax.swing.JDialog jd_mensaje;
    private javax.swing.JDialog jd_opcionesBuscar;
    private javax.swing.JDialog jd_principal;
    private javax.swing.JDialog jd_telefono;
    private javax.swing.JDialog jd_videollamada;
    private javax.swing.JLabel jl_labelWebcam;
    private javax.swing.JLabel jl_tiempoLlamada;
    private javax.swing.JLabel jl_tiempoVideollamada;
    private javax.swing.JTable jt_bitacora;
    private javax.swing.JTable jt_buzon;
    private javax.swing.JTable jt_contactos;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_apellidoBuscar;
    private javax.swing.JTextField tf_apellidoBuscarOpciones;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreBuscar;
    private javax.swing.JTextField tf_nombreBuscarOpciones;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
    Connection connect;
    Hilo thread;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    String nombreBuscar, apellidoBuscar;
    ArrayList listaCambio = new ArrayList();
    HiloTimer tiempoLlamada = new HiloTimer(this.jl_tiempoLlamada);
    HiloTimer tiempoVideollamada = new HiloTimer(this.jl_tiempoVideollamada);
    
    public void conectarBaseDatos() {
        try {
            String connectionUrl = "jdbc:sqlserver://;database=TablasLenguajes;integratedSecurity=true;";
            connect = DriverManager.getConnection(connectionUrl);
            System.out.println("Se ha conectado exitosamente.");
        } catch (SQLException ex) {
            System.out.println("Ha ocurrido un error.");
            ex.printStackTrace();
        }
    }
    
    public void usuarioTextField() {
        if (this.isVisible() && !this.tf_usuario.isFocusOwner()) {
            this.tf_usuario.grabFocus();
        }
    }

    public void contraTextField() {
        if (this.isVisible() && !this.tf_contra.isFocusOwner()) {
            this.tf_contra.grabFocus();
        }
    }
    
    public void nombreTextField(String nombre) {
        if (this.getFocusOwner() instanceof JTextField) {
            ((JTextField)this.getFocusOwner()).setText(nombre);
        }
    }
    
    public void nombreBuscarTextField() {
        if (this.isVisible() && !this.tf_nombreBuscar.isFocusOwner()) {
            this.tf_nombreBuscar.grabFocus();
        }
    }

    public void apellidoBuscarTextField() {
        if (this.isVisible() && !this.tf_apellidoBuscar.isFocusOwner()) {
            this.tf_apellidoBuscar.grabFocus();
        }
    }

    public void enseñarCrear(){
        this.jd_crear.setModal(true);
        this.jd_crear.pack();
        this.jd_crear.setLocationRelativeTo(this);
        this.jd_crear.setVisible(true);
    }
    
    public void enseñarBitacora(){
        this.jd_bitacora.setModal(true);
        this.jd_bitacora.pack();
        this.jd_bitacora.setLocationRelativeTo(this);
        this.jd_bitacora.setVisible(true);
    }
    
    public void enseñarBuscar(){
        this.jd_buscar.setModal(true);
        this.jd_buscar.pack();
        this.jd_buscar.setLocationRelativeTo(this);
        this.jd_buscar.setVisible(true);
    }
    
    public void enseñarBuzon(){
        this.jd_opcionesBuscar.setVisible(false);
        this.jd_buzon.setModal(true);
        this.jd_buzon.pack();
        this.jd_buzon.setLocationRelativeTo(this);
        this.jd_buzon.setVisible(true);
    }
    
    public void enseñarVideollamada(){
        this.jd_videollamada.setModal(true);
        this.jd_videollamada.pack();
        this.jd_videollamada.setLocationRelativeTo(this);
        this.jd_videollamada.setVisible(true);
    }
    
    public int conteoParaBitacora() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(fecha) from Bitacora;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
     int conteoParaContactos() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(numero) from Contacts;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
    public int conteoParaMensaje() {
        int temp = 0;
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select count(fecha) from Mensaje;");
            while (rs.next()) {
                temp = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return temp;
    }
    
    public String[] nombreBitacora() {
        String[] nombre = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoBitacora() {
        String[] apellido = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public String[] fechaBitacora() {
        String[] fecha = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select fecha from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                fecha[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fecha;
    }
    
    public String[] accionBitacora() {
        String[] accion = new String[conteoParaBitacora()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select accion from Bitacora;");
            int contador = 0;
            while (rs.next()) {
                accion[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return accion;
    }
    
    public int[] numeroContactos() {
        int[] numero = new int[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select numero from Contacts;");
            int contador = 0;
            while (rs.next()) {
                numero[contador] = rs.getInt(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return numero;
    }
    
    public String[] nombreContactos() {
        String[] nombre = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Contacts;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoContactos() {
        String[] apellido = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Contacts;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public String[] mailContactos() {
        String[] mail = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select email from Contacts;");
            int contador = 0;
            while (rs.next()) {
                mail[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return mail;
    }
    
    public String[] generoContactos() {
        String[] genero = new String[conteoParaContactos()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select genero from Contacts;");
            int contador = 0;
            while (rs.next()) {
                genero[contador] = rs.getString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return genero;
    }
    
    public String[] fechaMensaje() {
        String[] fecha = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select fecha from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                fecha[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fecha;
    }
    
    public String[] mensajeMensaje() {
        String[] mensaje = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select mensaje from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                mensaje[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return mensaje;
    }
    
    public String[] nombreMensaje() {
        String[] nombre = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select nombre from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                nombre[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return nombre;
    }
    
    public String[] apellidoMensaje() {
        String[] apellido = new String[conteoParaMensaje()];
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select apellido from Mensaje;");
            int contador = 0;
            while (rs.next()) {
                apellido[contador] = rs.getNString(1);
                contador++;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return apellido;
    }
    
    public ArrayList listaParaCambio(String nombreBuscar, String apellidoBuscar){
        ArrayList lista = new ArrayList();
        try {
            Statement statement = connect.createStatement();
            ResultSet rs;
            rs = statement.executeQuery("select numero from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getInt(1));
            }
            rs = statement.executeQuery("select nombre from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select apellido from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select email from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
            rs = statement.executeQuery("select genero from Contacts where nombre = '" + nombreBuscar + "'and apellido = '" + apellidoBuscar + "'");
            while (rs.next()) {
                lista.add(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return lista;
    }
    
    public void cambiarNumero() {
        String nuevo = JOptionPane.showInputDialog(this, "Escriba el nuevo numero", "Cambio de numero"
                ,JOptionPane.QUESTION_MESSAGE);
        int opcion = JOptionPane.OK_OPTION;
        int nuevoNumero = Integer.parseInt(nuevo);
        if (opcion == 0) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?");
                    update.setInt(1, nuevoNumero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el numero.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el numero de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
    
    public void cambiarNombre() {
        String nuevoNombre = JOptionPane.showInputDialog(this, "Escriba el nuevo nombre", "Cambio de nombre"
                ,JOptionPane.QUESTION_MESSAGE);
        int opcion = JOptionPane.OK_OPTION;
        if (opcion == 0) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?");
                    update.setInt(1, numero);
                    update.setString(2, nuevoNombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el nombre.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el nombre de un contacto");
                preparedStatement.setString(3, nuevoNombre);
                preparedStatement.setString(4, apellidoBuscar);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
    
    public void cambiarApellido() {
        String nuevoApellido = JOptionPane.showInputDialog(this, "Escriba el nuevo apellido", "Cambio de apellido"
                ,JOptionPane.QUESTION_MESSAGE);
        int opcion = JOptionPane.OK_OPTION;
        if (opcion == 0) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String mail = (String)listaCambio.get(3);
                String genero = (String)listaCambio.get(4);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, nuevoApellido);
                    update.setString(4, mail);
                    update.setString(5, genero);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el nombre.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el nombre de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, nuevoApellido);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
    
    public void cambiarMail() {
        String nuevoMail = JOptionPane.showInputDialog(this, "Escriba el nuevo email", "Cambio de email"
                ,JOptionPane.QUESTION_MESSAGE);
        int opcion = JOptionPane.OK_OPTION;
        if (opcion == 0) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String genero = (String)listaCambio.get(4);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, nuevoMail);
                    update.setString(5, genero);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el email.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el email de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
    
    public void cambiarGenero() {
        String nuevoGenero = JOptionPane.showInputDialog(this, "Escriba el nuevo genero", "Cambio de genero"
                ,JOptionPane.QUESTION_MESSAGE);
        int opcion = JOptionPane.OK_OPTION;
        if (opcion == 0) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                int numero = (Integer)listaCambio.get(0);
                String nombre = (String)listaCambio.get(1);
                String apellido = (String)listaCambio.get(2);
                String mail = (String)listaCambio.get(3);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement update = connect.prepareStatement("update Contacts set numero = ?"
                            + ", nombre = ?, apellido = ?, email = ?, genero = ?");
                    update.setInt(1, numero);
                    update.setString(2, nombre);
                    update.setString(3, apellido);
                    update.setString(4, mail);
                    update.setString(5, nuevoGenero);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha cambiado el genero.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha cambiado el genero de un contacto");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
    public void borrarContacto(){
        int seguro = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este contacto?");
        if (seguro == JOptionPane.YES_OPTION) {
            try {
                listaCambio = listaParaCambio(nombreBuscar,apellidoBuscar);
                Statement statement = connect.createStatement();
                ResultSet rs;
                rs = statement.executeQuery("select* from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                while (rs.next()) {
                    PreparedStatement delete = connect.prepareStatement("delete from Contacts where nombre = '"+nombreBuscar+"'and apellido = '"+apellidoBuscar+"'");
                    delete.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Se ha borrado el contacto.");
                }
                PreparedStatement preparedStatement = connect.prepareStatement("Insert into Bitacora values (?,?,?,?)");
                preparedStatement.setString(1, dtf.format(LocalDateTime.now()));
                preparedStatement.setString(2, "Se ha borrado un contacto.");
                preparedStatement.setString(3, nombreBuscar);
                preparedStatement.setString(4, apellidoBuscar);
                int prueba = preparedStatement.executeUpdate();
                if (prueba > 0) {
                    System.out.println("Bitacora actualizada.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            this.jd_opcionesBuscar.setVisible(false);
        }
    }
}
